# Generated by Django 4.2.5 on 2024-01-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0019_contact_form'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_req',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='user_req',
            name='req_msg',
        ),
        migrations.AddField(
            model_name='user_req',
            name='h_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadmin.house'),
        ),
        migrations.AddField(
            model_name='user_req',
            name='req_mes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_req',
            name='req_type',
            field=models.BooleanField(default=0),
        ),
    ]
