# Generated by Django 4.2.5 on 2024-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_user_user_req_student_remove_user_req_req_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_req',
            name='sharing',
            field=models.IntegerField(default=1),
        ),
    ]
