# Generated by Django 4.2.5 on 2024-01-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_req_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_req',
            name='req_type',
            field=models.IntegerField(default=0),
        ),
    ]
