# Generated by Django 4.2.5 on 2024-01-30 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0020_notification_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0004_alter_user_req_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_req',
            name='req_accept_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_staff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_req',
            name='h_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadmin.house'),
        ),
    ]
