# Generated by Django 4.2.5 on 2024-01-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_req_req_accept_staff_alter_user_req_h_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_req',
            name='req_mes',
        ),
        migrations.RemoveField(
            model_name='user_req',
            name='sharing',
        ),
    ]
