# Generated by Django 4.2.5 on 2023-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_address', models.CharField(max_length=255)),
                ('staff_phone', models.BigIntegerField()),
                ('staff_dob', models.DateField()),
                ('staff_status', models.BooleanField(default=True)),
            ],
        ),
    ]
