# Generated by Django 4.2.5 on 2024-01-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_details',
            name='staff_address',
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_country',
            field=models.CharField(default='Not specified', max_length=30),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_land_mark',
            field=models.CharField(default='Not specified', max_length=70),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_locality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='staff_state',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
