# Generated by Django 4.2.5 on 2024-01-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_remove_staff_details_staff_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_details',
            name='staff_name',
        ),
    ]
