# Generated by Django 4.2.5 on 2024-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_alter_usertype_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_number', models.CharField(default='Not specified', max_length=50)),
                ('hs_street', models.CharField(default='Not specified', max_length=50)),
                ('hs_city', models.CharField(default='Lavasa', max_length=50)),
                ('hs_state', models.CharField(default='Maharastra', max_length=50)),
                ('hs_country', models.CharField(default='India', max_length=50)),
                ('hs_pin', models.BigIntegerField(default='412112')),
                ('hs_bhk', models.CharField(default='Not specified', max_length=6)),
                ('hs_rent', models.BigIntegerField(default='0')),
                ('hs_desc', models.TextField(default='Not specified')),
                ('hs_status', models.BooleanField(default=True)),
            ],
        ),
    ]
