# Generated by Django 4.2.5 on 2024-01-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0007_alter_staff_details_staff_img'),
        ('cadmin', '0008_house_hs_owner'),
    ]

    operations = [
    ]
