# Generated by Django 4.2.5 on 2024-01-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0009_merge_20240118_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='House Images')),
                ('img_status', models.BooleanField(default=True)),
                ('h_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cadmin.house')),
            ],
        ),
    ]
