# Generated by Django 4.2.5 on 2024-01-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0010_h_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_name', models.CharField(max_length=100)),
                ('Street_address', models.CharField(max_length=255)),
                ('Street_status', models.BooleanField(default=True)),
                ('Street_imaage', models.ImageField(upload_to='Streets')),
            ],
        ),
    ]
