# Generated by Django 4.2.5 on 2024-01-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0011_streets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streets',
            old_name='Street_imaage',
            new_name='Street_image',
        ),
    ]
