# Generated by Django 4.2.5 on 2024-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0018_remove_house_hs_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=150)),
                ('ph_no', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
