# Generated by Django 4.2.5 on 2024-01-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0019_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
