# Generated by Django 4.2.5 on 2024-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0026_house_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='hs_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='House_Images'),
        ),
        migrations.AddField(
            model_name='house',
            name='hs_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='House_Images'),
        ),
        migrations.DeleteModel(
            name='h_img',
        ),
    ]
